
name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        timestamp=$(date '+%Y-%m-%d %H:%M:%S')
        curl https://api.waqi.info/feed/los-angeles/?token=a44d4136cd7e57a2a186f2a04412a15ecc536171 | jq . > "data/reading_${timestamp}_UTC.json"
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
